# numpy

In [19]:
import numpy as np

#arr = np.array([1, 2, 3, 4, 5])
#arr = np.array([[1, 2, 3],[4, 5,6]])
arr = np.array([[[1, 2, 3],[4, 5,6]],
                [[1, 2, 3],[4, 5,6]]])


print(type(arr))

<class 'numpy.ndarray'>


In [20]:
print(arr.shape) #배열 형태
print(arr.dtype) #요소의 데이터 타입
print(arr.ndim) #차원 수
print(arr.size) #요소의 개수(shape의 모든 값의 곱)
print(arr.itemsize) #요소의 데이터 타입의 크기
print(arr.data) #실제 데이터 직접 사용자가 접근 할 필요는 없음

(2, 2, 3)
int32
3
12
4


In [28]:
arr = np.ones((2,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [29]:
arr = np.full((2,3),10)
print(arr)

[[10 10 10]
 [10 10 10]]


In [40]:
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [44]:
arr = np.array([[[1,2,3,],[4,5,6]],
               [[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
print(arr[0,:]) #0행 모든열
print(arr[:,0]) #모든행 0열
print(arr[0:2, :-1]) #0행~1행, 처음부터 마지막열까지

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]
[[[1 2 3]]

 [[7 8 9]]]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [1]:
arr = [1, 2, 3, 4, 5]
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])

print(arr)
print(arr.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [7]:
arr = np.arange(15).reshape(3, 5)
rarr = arr.reshape(5, 3)

print(arr)
print(rarr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
